"""
SQLAlchemy ORM model for CI2D3 Ice Island data
"""
from sqlalchemy import Column, Integer, String, Float, Date, Text
from sqlalchemy.ext.declarative import declarative_base
from geoalchemy2 import Geometry

Base = declarative_base()


class IceIsland(Base):
    """
    Ice Island model representing the CI2D3 dataset

    Table structure will be created when loading shapefile into PostGIS
    This model maps to the existing table structure
    """
    __tablename__ = 'iceislands'

    # Primary key (will be auto-generated by PostGIS)
    gid = Column(Integer, primary_key=True, autoincrement=True)

    # Geometry column (polygon in EPSG:5937 - Canada Lambert Conformal Conic)
    geom = Column(Geometry('POLYGON', srid=5937))

    # Ice Island attributes - these will match the shapefile schema
    # Note: Actual column names will be determined by the shapefile DBF structure
    # Common attributes expected in CI2D3 dataset:

    objectid = Column(Integer)
    iceisland_id = Column(String(100))  # Unique ice island identifier
    calvingloc = Column(String(50))     # Calving location code (CG, NA, NG, PG, RG, SG)
    calvingdate = Column(Date)          # Date of calving event
    carving_year = Column(Integer)      # Year of calving
    area_km2 = Column(Float)            # Area in square kilometers
    perimeter_km = Column(Float)        # Perimeter in kilometers
    max_length_km = Column(Float)       # Maximum length
    max_width_km = Column(Float)        # Maximum width
    thickness_m = Column(Float)         # Ice thickness in meters
    source_glacier = Column(String(200))  # Source glacier name
    drift_track = Column(String(50))    # Drift trajectory identifier
    status = Column(String(50))         # Current status (active, grounded, melted, etc.)
    last_observed = Column(Date)        # Last observation date
    notes = Column(Text)                # Additional notes

    def to_dict(self):
        """Convert model instance to dictionary"""
        return {
            'gid': self.gid,
            'objectid': self.objectid,
            'iceisland_id': self.iceisland_id,
            'calvingloc': self.calvingloc,
            'calvingdate': self.calvingdate.isoformat() if self.calvingdate else None,
            'carving_year': self.carving_year,
            'area_km2': self.area_km2,
            'perimeter_km': self.perimeter_km,
            'max_length_km': self.max_length_km,
            'max_width_km': self.max_width_km,
            'thickness_m': self.thickness_m,
            'source_glacier': self.source_glacier,
            'drift_track': self.drift_track,
            'status': self.status,
            'last_observed': self.last_observed.isoformat() if self.last_observed else None,
            'notes': self.notes
        }

    def __repr__(self):
        return f"<IceIsland(id={self.iceisland_id}, location={self.calvingloc})>"
